config/routes.rb
Rails.application.routes.draw do
  root to: 'reviews#index'
  get 'get_reviews', to: 'reviews#get_reviews', as: 'get_reviews'
  get 'narrow_down_suggestions', to: 'reviews#narrow_down_suggestions', as: 'narrow_down_suggestions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  	
  end

  def narrow_down_suggestions
    @results_count = params[:results_count]
    @suggestions = YelpSearch.new(params[:query], limit: @results_count).search_options
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js {}
    end
  end

  def get_reviews
    @results_count = params[:results_count]
    @reviews = YelpSearch.new(params[:url], limit: @results_count).specific_reviews
    @reviews_presenter = ReviewsPresenter.new(@reviews)
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js {}
    end
  end


end

app/controllers/reviews_controller/reviews_presenter.rb
class ReviewsController::ReviewsPresenter

	def initialize(reviews)
		@reviews = reviews 
	end

	def average_stars
		stars = @reviews.map(&:stars).compact.keep_if {|r| r.to_f == r}
		stars.inject{ |sum, el| sum + el.to_f } / stars.count
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slice-o-matic</title>
    <%= csrf_meta_tags %>
		<style>
			@import url('https://fonts.googleapis.com/css?family=Open+Sans|Roboto');
		</style>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_narrow_down_suggestions.html.erb
<table class='table table-striped'>
	<tbody>
		<% Array(@suggestions).each do |suggestion| %> 
			<tr>
				<td class='narrow-down-review' data-url = <%=suggestion.link%> >
					<%= suggestion.title %> 
				</td>
				<td>
					<%= suggestion.stars %> 
				</td>
			</tr>
		<% end %>
	</tbody>

</table>

<script>
	$('.narrow-down-review').on('click',function(){
		var url = $(this).data('url');
		var resultsCount = $('#results-count').val();
		$.ajax({
		    type: "GET",
		    url: '<%=get_reviews_path%>.js',
		    data: {url: url, results_count: resultsCount},
			  dataType: 'script'
		});
	})
</script>

app/views/reviews/_reviews.html.erb
<% if @reviews_presenter %> 
	<div class="col-xs-12 stars-container">
		<%= render partial: 'stars', locals: {stars: @reviews_presenter.average_stars } %> 
	</div>
<% end %> 

<table class='table table-striped reviews-table'>
	<tbody>
		<% Array(@reviews).each do |review| %> 
			<tr >
				<td>
					<%= review.content %> 
				</td>
				<td>
					<%= review.stars %> 
				</td>
			</tr>
		<% end %>
	</tbody>

</table>

app/views/reviews/_stars.html.erb
Average stars: 
<% stars.to_i.times do %>
	<i class="fa fa-star" aria-hidden="true"></i>
<% end %> 
<% if stars.to_f - stars.to_i == 0.5 %> 
	<i class="fa fa-star-half-o" aria-hidden="true"></i>
<% end %> 
(<%=stars.to_f.round(1)%>)

app/views/reviews/get_reviews.js.erb
$('.reviews-container').html('<%= escape_javascript(render("reviews")) %>');
$('.narrow-down-suggestions-container ').hide();
$('.reviews-container ').show();

app/views/reviews/index.html.erb
<div class="container">
	<div class="container text-center">
		<div class="col-xs-12">
			<span class='title-bold'> Get Pizza Reviews</span>
		</div>
		<div class="col-xs-12">
			<%= image_tag('pizza_logo.jpeg', alt: 'pizza slice', id: 'pizza-logo') %> 
		</div>
		
		
	</div>
	<%= form_tag(narrow_down_suggestions_path, :method => "get", id: "search-form", remote: true) do %>
		<div class="col-xs-12 col-sm-3">
			<label for="results_count">Search for</label>
	    <%= text_field_tag :results_count, params[:results_count], id: 'results-count', value: "10", class: 'form-control' %>
	    <small id="emailHelp" class="form-text text-muted">Up to a maximum of 10.</small>
		</div>
		<div class="col-xs-12 col-sm-9">
			<label for="query">pizza places named:</label>
	    <%= text_field_tag :query, params[:query], placeholder: "Search Reviews", class: 'form-control', placeholder: 'Gino\'s Pizza' %>
		</div>
		<div class="form-section col-xs-12">
			<%= submit_tag "Search", :name => nil, class: 'btn btn-success pull-right' %>
		</div>
	    
	<% end %>
	
	<div class="narrow-down-suggestions-container" style="display: none">
		Did you mean? 
		<%= render 'narrow_down_suggestions' %>
	</div>

	<div class="reviews-container"> 
		<%= render 'reviews' %>
	</div>

</div>

app/views/reviews/narrow_down_suggestions.js.erb
$('.narrow-down-suggestions-container').html('<%= escape_javascript(render("narrow_down_suggestions")) %>');
$('.narrow-down-suggestions-container').show();
$('.reviews-container ').hide();